# Generated by Django 5.2.10 on 2026-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_usersensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
